-- MySQL Script generated by MySQL Workbench
-- Thu Jan 20 15:20:47 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pruebapracticabd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pruebapracticabd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pruebapracticabd` DEFAULT CHARACTER SET utf8 ;
USE `pruebapracticabd` ;

-- -----------------------------------------------------
-- Table `pruebapracticabd`.`rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pruebapracticabd`.`rol` ;

CREATE TABLE IF NOT EXISTS `pruebapracticabd`.`rol` (
  `idrol` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idrol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pruebapracticabd`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pruebapracticabd`.`usuario` ;

CREATE TABLE IF NOT EXISTS `pruebapracticabd`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `activo` CHAR(30) NOT NULL,
  `rol_idrol` INT NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_rol_idx` (`rol_idrol` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_rol`
    FOREIGN KEY (`rol_idrol`)
    REFERENCES `pruebapracticabd`.`rol` (`idrol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
